CREATE TABLE "ORDERS_NEW" (
	"ID" INTEGER PRIMARY KEY AUTOINCREMENT,
	"PRODUCT_ID" INTEGER NOT NULL,
	"CUSTOMER_ID" INTEGER NOT NULL,
	FOREIGN KEY ("PRODUCT_ID") REFERENCES Products("ID"),
	FOREIGN KEY ("CUSTOMER_ID") REFERENCES Customer("ID")
	);
	
