CREATE TABLE "ORDERS" (
	"PRODUCT_ID" INTEGER NOT NULL,
	"CUSTOMER_ID" INTEGER NOT NULL,
	PRIMARY KEY ("PRODUCT_ID", "CUSTOMER_ID"),
	FOREIGN KEY ("PRODUCT_ID") REFERENCES Products("ID"),
	FOREIGN KEY ("CUSTOMER_ID") REFERENCES Customer("ID")
	);
	
